version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "workshop"
s3_bucket="aws-sam-cli-thomas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
